### PR TITLE
Make scrollToTime=00:00 working

### LINKED ISSUE #1474: BUG: scrollToTime 00h:00m doesn't work
#### Do you want to request a _feature_ or report a _bug_?
Report a bug

#### What's the current behavior?

scrollToTime prop does not work if the value's date has `00h 00m`

demo: https://codesandbox.io/embed/react-big-calendar-issue-scrolltotime-dp9zy
video: https://monosnap.com/file/dP5aEOh73L2K7Z7IfU2XJQtNnxdtJS

It mostly likely happens because of this check https://github.com/intljusticemission/react-big-calendar/blob/master/src/TimeGrid.js#L261 - scrollToTime is not being applied because `this._scrollRatio` is zero (false) (calculated at line https://github.com/intljusticemission/react-big-calendar/blob/master/src/TimeGrid.js#L275)

#### What's the expected behavior?

view scrolls to top when scrollToTime has been set to `00h:00m`

### PR DESCRIPTION
**Pull request by amok**
fixes #1474

### CODE REVIEW

File: src/TimeGrid.js [hunk 1]
```diff
@@ -267,7 +268,7 @@ export default class TimeGrid extends Component {
   }
 
   applyScroll() {
-    if (this._scrollRatio) {
+    if (typeof this._scrollRatio === 'number') {
```
Comment (jquense) [inline src/TimeGrid.js]: `this._scrollRatio != null`

Comment (amok) [reply src/TimeGrid.js]: @jquense done

**Comment by jquense** [comment]
thanks!
